# This workflow will do a clean install of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Dist

on:
    push:
        branches: [ main ]

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v2
            - uses: pnpm/action-setup@v2.0.1
              with:
                  version: 6.15.1
            - run: pnpm install
            - name: Use Node.js
              uses: actions/setup-node@v2
              with:
                  cache: 'pnpm'
            - run: pnpm build
            - run: |
                git config user.name github-actions
                git config user.email github-actions@github.com
                git add .
                git commit -m "generated"
                git push
